--- #YAML:1.0
name:               Akado-Account
version:            0.02
abstract:           get internet provider Akado account info
author:
    - Ivan Bessarabov <ivan@bessarabov.ru>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:         0
    XML::XPath:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
